### ISSUE TITLE
Normalize content of the sources bundles

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-embed-cdt/eclipse-plugins#402]
From #397 by @ilg-ul 

> ...  I checked some source .jar files, and they only include the ilg.gnumcueclipse.* folders, and some minimal metadata.
> 
> All other files were skipped. When I check in Eclipse the build.properties file, the Binary Build lists has most files selected, but the Source Build section has no files selected at all. Is this ok?

Let's use Eclipse Platform bundles as a sample to normalize the content

**Comment by ilg-ul** [comment]
> Let's use Eclipse Platform bundles as a sample to normalize the content

Good plan.

I would also take a look at the CDT projects.

**Comment by ilg-ul** [comment]
Please note that the SiFive template project has some git submodules, with the code used to create RISC-V projects.

(Comment moved here from #397).

**Comment by ruspl-afed** [comment]
> I would also take a look at the CDT projects.
Yes, to fix it too :)

**Comment by ilg-ul** [comment]
#404 is the only change required?

**Comment by ruspl-afed** [comment]
It looks so, I walked through all the bundles that I can see.

**Comment by ilg-ul** [comment]
Ok, when done, you can close the issue.

I changed the strategy, I no longer keep them open until the actual release, I tag them with a milestone and it is enough to keep track of the changes related to a release.
