### ISSUE TITLE
GDB path not set correct

### ISSUE THREAD

**Issue by mgiaco** [eclipse-embed-cdt/eclipse-plugins#409]
Hi,
I use the latest tools (xpacks gcc, xpack openocd and build tools, Eclipse 2020-06 with latest updates and openjdk14). I think there is something wrong in the gdb path setting. 
When I start a GDB session eclipse do not use the xpack path. 
When I set the Executable name in the GDB Client Setup in the debug launch setting everything works fine.

**Comment by ilg-ul** [comment]
> When I start a GDB session eclipse do not use the xpack path.

Then you have a path problem. 

Download a new eclipse package, install it in a separate location, create a new workspace and run the blinky arm tutorial.

**Comment by ilg-ul** [comment]
Any progress?

**Comment by mgiaco** [comment]
Hi, I found out that the java version is the problem i switched to openjdk 14. Made a new worksspace and everything works fine.

**Comment by ilg-ul** [comment]
Your initial message also mentioned openjdk14. What platform are you using?

**Comment by mgiaco** [comment]
The problem was eclipse did not start with openjdk 14.

**Comment by ilg-ul** [comment]
And now what java are you using?

**Comment by mgiaco** [comment]
openjdk 14.

**Comment by ilg-ul** [comment]
Aha, so you claim that 'eclipse did not start with openjdk 14' and that now you are using openjdk 14. Does it make any sense?

**Comment by mgiaco** [comment]
On my machine there was the latest open version from Oracle installed (java version "1.8.0_261") and openjdk 14. But the path was pointed to the Oracel java and i did not check that. So for the first time i taught I am using openjdk 14.... 
No I added the following line in eclipse.ini 
-vm
c:\openjdk-14.0.2_windows-x64_bin\jdk-14.0.2\bin\

and now everything works fine.

**Comment by ilg-ul** [comment]
Right, all recent Eclipse require Java 11, this is already mentioned in the old web site.

I added a Prerequisites section in the download page:

https://projects.eclipse.org/projects/iot.embed-cdt/downloads
