### ISSUE TITLE
Configure the Java xml parser to accept files that start with the BOM sequence

### ISSUE THREAD

**Issue by rbresalier** [eclipse-embed-cdt/eclipse-plugins#412]
This issue is in reference to forum conversation:

https://www.tapatalk.com/groups/xpack/perhipheral-view-is-empty-t79.html

The peripheral view was empty because the svd file started with BOM sequence: ef bb bf 3c

As requested, I'm creating this issue for an enhancement to configure the java xml parser to properly handle these BOM sequences.

**Comment by ilg-ul** [comment]
The Java processing of BOM is known to be problematic:

- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4508058
- http://bugs.sun.com/view_bug.do?bug_id=6378911

In addition, Unicode says "Use of a BOM is neither required nor recommended for UTF-8".

Given that there is no simple way to fix this in Java, I'm afraid I have to tag this bug as unfixable and close this bug.
