### ISSUE TITLE
About debugging or run tools for toolbars

### ISSUE THREAD

**Issue by laomaolaile** [eclipse-embed-cdt/eclipse-plugins#416]
At  GNU MCU Eclipse plug-ins v4.7.2-202001271244 and Before version , there is a convenient tool to run and debug in the toolbar. But at Eclipse Embedded CDT plug-ins v5.1.1-20200727 After version , there is no such tool. How can I continue to use this tool.

**Comment by ilg-ul** [comment]
You can enable the Launchbar in the Eclipse Preferences pages (Run/Debug > Launching > Launch Bar)

For further questions and support, please use the project forum.
