### ISSUE TITLE
Split Java code between core & UI for Embedded CDT Packs

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-embed-cdt/eclipse-plugins#440]
Extracted from #428 

The following bundles should be available in headless context:
* org.eclipse.embedcdt.packs
* org.eclipse.embedcdt.packs.core
* org.eclipse.embedcdt.packs.data

**Comment by ilg-ul** [comment]
Alexander @ruspl-afed, I had to revert some commits in master, please be sure you somehow merge them to the `develop-split` branch.

**Comment by ilg-ul** [comment]
I guess #441 fixed this.
