### ISSUE TITLE
Documents image trademark

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-embed-cdt/eclipse-plugins#442]
The there is this image ![pdf icon](https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/efad1edb759dab5bcb2533ac781ff892fb9eed85/plugins/org.eclipse.embedcdt.packs.ui/icons/pdficon_small.png?raw=true) replicated a few times in embed-cdt plugins. Do we have permission to use Acrobat logo here?

The icon appears in the Documents view (other places too?):

![image](https://user-images.githubusercontent.com/679236/100461706-2a220680-3097-11eb-8d90-d12708c99767.png)

**Comment by ilg-ul** [comment]
Do you have any suggestion how to address this?

**Comment by jonahgraham** [comment]
Quick solution is to just create a simple PDF icon, or if there is suitably licensed one out there we can create a CQ to reuse it.

If you want I can handle this, there may be an icon in Eclipse icon repo already that is suitable.

**Comment by ilg-ul** [comment]
Sure, if you want, please handle it.

**Comment by jonahgraham** [comment]
Step 1 - here are the icons - converted from SVG to PNG with [eclipse image renderer](https://git.eclipse.org/r/plugins/gitiles/platform/eclipse.platform.images/+/refs/heads/master/org.eclipse.images.renderer/) SVG created with Inkscape based on a standard blank document (I used the document from [ant_buildfile.svg](https://git.eclipse.org/r/plugins/gitiles/platform/eclipse.platform.images/+/refs/heads/master/org.eclipse.images/eclipse-svg/org.eclipse.ant.ui/icons/full/obj16/ant_buildfile.svg))

[PDF of SVG + generated png](https://github.com/eclipse-embed-cdt/eclipse-plugins/files/5611545/pdficon.zip)

The Hi-DPI image looks ok, the low res one is less than perfect, but ok for a first try.

Step 2 - I will do a PR with these images replacing the existing ones later.

**Comment by ilg-ul** [comment]
Ok, thank you.

**Comment by jonahgraham** [comment]
> Step 2 - I will do a PR with these images replacing the existing ones later.

Done. See PR #447

**Comment by ilg-ul** [comment]
Thank you, I merged it.

Regarding HI-DPI, I never tried the plug-ins on such display. Do they display properly?

**Comment by jonahgraham** [comment]
My current setup is not hidpi, I have access to one if I need to. I just followed the standard practice of the @2x which automagically does the correct thing in most cases. If a @2x image isn't found, then Eclipse will scale up a normal image.

Your Mac isn't hidpi by default? I thought most macs were.

**Comment by ilg-ul** [comment]
My Mac is, but the monitor is only 1920x1200.

**Comment by jonahgraham** [comment]
There is some stuff [here](https://www.eclipse.org/eclipse/news/4.6/platform.php#swt-autoscale) - I think you can force scaling, but I haven't played with it much. 

This issue is done now. Thanks for merging the change.
