### ISSUE TITLE
Add Eclipse-SourceReferences

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-embed-cdt/eclipse-plugins#450]
Add Eclipse-SourceReferences to MANIFEST.MF

**Comment by ilg-ul** [comment]
Could you add a line here explaining what this means?

**Comment by jonahgraham** [comment]
Read all about it in this dated article https://wiki.eclipse.org/PDE/UI/SourceReferences

**Comment by ilg-ul** [comment]
I ran a local build and it showed the extra line in MANIFEST.MF, so I guess it is ok.

Thank you!
