### ISSUE TITLE
Reformat code to CDT style

### ISSUE THREAD

**Issue by ilg-ul** [eclipse-embed-cdt/eclipse-plugins#457]
At a certain moment the CDT code was reformatted to a given style.

Can we do the same for the Embed CDT code?

**Comment by jonahgraham** [comment]
Yes - I can do that. CDT is very strict now and will reject a PR that breaks the code formatting and whitespace. We can adapt that here is desired too.

One change means that the .settings for each project should be checked in and the project will store the formatting settings.

Big problem is I don't know if I can do this before 6.0.0 (Tuesday). I will try though and give an update later.

**Comment by ilg-ul** [comment]
Please merge everything to develop and create a new branch from there.

**Comment by ilg-ul** [comment]
> CDT is very strict now and will reject a PR that breaks the code formatting and whitespace. We can adapt that here is desired too

Yes, that would be nice, but I guess we can do it in a second step, for now simply reformatting everything would be enough.

**Comment by ilg-ul** [comment]
At a second thought I guess we can do this after Tuesday, better to keep the code ready in case we need to patch something else before Tuesday.

**Comment by ilg-ul** [comment]
My simplistic view of the subject is that we take the `formatsettings.xml` from CDT, select everything and with Source -> Format fix all files.

If this is not realistic, we'll definitely leave it for after Tuesday.

**Comment by ilg-ul** [comment]
Jonah, I think we're ready with all changes, and we can proceed with code reformatting.

**Comment by jonahgraham** [comment]
> My simplistic view of the subject was that we take the `formatsettings.xml` from CDT, select everything and with Source -> Format fix all files.

That is one option - I provided in #469  what we do for CDT which is more heavy weight, but helps to keep the code formatted by other contributors in sync with embedcdt because the settings are stored with projects instead of the workspace.
