### ISSUE TITLE
A problem about openocd

### ISSUE THREAD

**Issue by laomaolaile** [eclipse-embed-cdt/eclipse-plugins#462]
![image](https://user-images.githubusercontent.com/19726057/102197040-986e2200-3efb-11eb-90cc-95cf5bde6e64.png)

When I created a project, I reported an error, as shown in the figure. This error does not appear every time. It is random and can be encountered occasionally. How can this be solved.

**Comment by laomaolaile** [comment]
![image](https://user-images.githubusercontent.com/19726057/102197500-3a8e0a00-3efc-11eb-9ca8-30bcff921de1.png)

**Comment by ilg-ul** [comment]
What template project are you using?

**Comment by laomaolaile** [comment]
It's a new template I created myself.
Under what circumstances will this error be corrected?

**Comment by ilg-ul** [comment]
Starting with the (just released) v6.0.0, the project was greatly restructured, so I suggest you first update your template to the new Java package names and Eclipse IDs.
