### ISSUE TITLE
how to get always visible launchbar in a custom eclipse plugin

### ISSUE THREAD

**Issue by fabiovito** [eclipse-embed-cdt/eclipse-plugins#473]
i want write a my custom eclipse plugin to turn-on the launchbar.
How can i turn-on an always visible launchbar?
i've seen that the eclipse embedded cdt package has disabled this feature of default and i must turn-on manually.

**Comment by ilg-ul** [comment]
The initial status of Arduinish launchbar is controlled by the `org.eclipse.launchbar.ui.controls/enableLaunchBar` property in the Eclipse `.ini` file.

**Comment by fabiovito** [comment]
how can i customize it in my plugin to have an always-on launchbar without manually change it in the eclipse.ini file ?

**Comment by ilg-ul** [comment]
I never tried this, I'm afraid you have to figure out yourself.
