### ISSUE TITLE
Template features don't include their own primary plug-in

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-embed-cdt/eclipse-plugins#481]
See for example how this feature does not include its corresponding bundle. This means that in the install that bundle is not present nor does it appear in the p2 site.

https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/37d2e4f1bf89f1d7ab57511bb6ca102f718b85d9/features/org.eclipse.embedcdt.templates.ad-feature/feature.xml#L20

I don't know full visible effects of this, but one of them is that Help -> About -> installation details -> Features tab does not display the feature.

**Comment by ilg-ul** [comment]
Fixed on 2021-01-20.
