### ISSUE TITLE
Some feature's (like codered) have suspect "import feature"

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-embed-cdt/eclipse-plugins#482]
Codered's requirement on org.eclipse.embedcdt has a `.qualifier` in the required version. I believe this is one of the places that can't be done. It is also odd that a version is specified, but no match attribute. See [feature spec](https://help.eclipse.org/2020-12/topic/org.eclipse.platform.doc.isv/reference/misc/feature_manifest.html?cp=2_1_5_19)

https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/37d2e4f1bf89f1d7ab57511bb6ca102f718b85d9/features/org.eclipse.embedcdt.codered-feature/feature.xml#L33

**Comment by ilg-ul** [comment]
Fixed on 2021-01-20.
