### ISSUE TITLE
The peripheral view is empty

### ISSUE THREAD

**Issue by zhaoxuji** [eclipse-embed-cdt/eclipse-plugins#491]
The problem description is like the title.
![1623031093(1)](https://user-images.githubusercontent.com/19777514/120949439-1c041f80-c777-11eb-9b71-9da34d87005f.png)
![1623031135(1)](https://user-images.githubusercontent.com/19777514/120949444-1eff1000-c777-11eb-8b30-7e0b8d60fd4b.png)

[log.txt](https://github.com/eclipse-embed-cdt/eclipse-plugins/files/6605422/log.txt)

**Comment by ilg-ul** [comment]
Your SVD files seem to contain non-parseable characters.

**Comment by jonahgraham** [comment]
@zhaoxuji Are you able to share the SVD file you used? The Xml reader (linked below) should be handling the encoding as declared in the SVD XML file. Is there a `encoding="utf-8"` or similar in the SVD? And if so, does it match the contents of the file?

https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/c57bac116b482ee102ebbeb875efdaea1cf25b32/plugins/org.eclipse.embedcdt.core/src/org/eclipse/embedcdt/core/Xml.java#L50-L59

**Comment by SoniaZotz** [comment]
having the same problem
![perif](https://user-images.githubusercontent.com/10633874/148854791-7bf69742-fb20-4c2e-878f-3277a8d6a840.jpg)
 
![image](https://user-images.githubusercontent.com/10633874/148854910-0f67366f-6f2e-4249-93d9-c0ddabbbc366.png)

**Comment by TommyMurphyTM1234** [comment]
> having the same problem

You probably need to post your SVD XML file.

**Comment by SoniaZotz** [comment]
standard ARM  Pscks -- Arm\Packs\NordicSemiconductor\nRF_DeviceFamilyPack\8.44.1\SVD
[nrf51.zip](https://github.com/eclipse-embed-cdt/eclipse-plugins/files/7850561/nrf51.zip)

**Comment by ilg-ul** [comment]
The file is ok, it was parsed properly:

![Screenshot 2022-01-12 at 10 48 21](https://user-images.githubusercontent.com/362732/149094308-903b1a49-d651-4481-88c6-6f706f0dd92c.png)

**Comment by SoniaZotz** [comment]
yes thank -its working  I used the wrong file in the SVD  selection
