### ISSUE TITLE
Not able to pass the commands to gdb client (In openocd plugin)

### ISSUE THREAD

**Issue by vidyatc** [eclipse-embed-cdt/eclipse-plugins#492]
When we pass commands in Commands(text field) and other options (text field) in the Debugger tab, the plugin does not accept those commands.

![image](https://user-images.githubusercontent.com/58321781/122364300-4627bf80-cf77-11eb-93b3-bb95af1ec607.png)

* plug-in version  - openocd 5.2.1
* Eclipse version - 2020-09 (4.17.0)
* operating system - Ubuntu 18

**Comment by ilg-ul** [comment]
> the plugin does not accept those commands.

Can you be more specific and describe what happens?

**Comment by vidyatc** [comment]
if we uncheck Load symbol and Load executable in startup and pass "load < file.exe >"  in commands(text field) it's throwing Failed to execute MI command
Error in final launch sequence
Failed to execute MI command:
load /home/performance-server/openocd/freedom-e-sdk/software/hello/hello
Error message from debugger back end:
You can't do that when your target is `None'
Failed to execute MI command:
load /home/performance-server/openocd/freedom-e-sdk/software/hello/hello
Error message from debugger back end:
You can't do that when your target is `None'
You can't do that when your target is `None'

**Comment by ilg-ul** [comment]
Can you compare the GDB trace output between the two cases?

What openocd binary are you using?

**Comment by TommyMurphyTM1234** [comment]
I suspect that putting the load command in the Debugger > GDB Client Setup > Commands field means that it happens before the target remote connection has been established. Have you tried putting it in the Startup > Initialization Commands section instead?

**Comment by TommyMurphyTM1234** [comment]
@vidyatc - did you try that I described?
@ilg-ul - I am pretty sure that this is not an issue with the Eclipse Embedded CDT plugins. In fact not an issue at all. :-)

**Comment by jonahgraham** [comment]
Thanks @TommyMurphyTM1234.

@vidyatc if there is more info that indicates a problem in embed cdt we can reopen. Let us know either way as it can help the next person who has a similar error.
