### ISSUE TITLE
Could we add support for AVR microcontroller and arduino framework?

### ISSUE THREAD

**Issue by TurnOffNOD** [eclipse-embed-cdt/eclipse-plugins#494]
AVR represents a type of MCU, which is designed to have more IO modules, with internal ADC and DAC support, and multiple PWM support. It is a relatively "pure" controller.
So, it is reasonable to have AVR support.

**Comment by ilg-ul** [comment]
As for arduino, I think there are other more specialised plug-ins.

As for AVR, it is an 8 bit architecture with lots of problems (for example not being able to conveniently access const strings in C/C++). I would say it is already obsolete, I'm not sure it is worth the effort.

**Comment by TommyMurphyTM1234** [comment]
FWIW this was asked before here

https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/309
