### ISSUE TITLE
Update logic to identify toolchains by ID, not by name

### ISSUE THREAD

**Issue by ilg-ul** [eclipse-embed-cdt/eclipse-plugins#522]
The current logic identifies toolchains by the name.

The new RISC-V toolchain showed that this might not be unique, and the toolchains must be identified by a long name, which includes the executable name.

Internally toolchains must be identified by the unique ID, which is an unsigned long, initially based on the Java hash, but not necessarily.

This should also fix the unexplained inconsistencies in IDs, in RISC-V configurations, like `toolchain.path.2021824384` vs `"...toolchain.id..."  ... value="2273142912", for `xPack GNU RISC-V Embedded GCC` (the correct hash is the value, not the path key).

Also the Linaro toolchains have unexpected IDs.

**Comment by ilg-ul** [comment]
Fixed on 2022-06-18.

**Comment by TommyMurphyTM1234** [comment]
Was this actually fixed or might there be some regression?

Steps to reproduce (on Ubuntu 24.04 LTS):

1. Download Eclipse 2025.03 R for Embedded C/C++ Developers tarball (from https://www.eclipse.org/downloads/packages/) and extract it:
```
wget https://eclipse.mirror.liteserver.nl/technology/epp/downloads/release/2025-03/R/eclipse-embedcpp-2025-03-R-linux-gtk-x86_64.tar.gz

tar xvf eclipse-embedcpp-2025-03-R-linux-gtk-x86_64.tar.gz

cd eclipse
```

2. Install latest RISC-V GCC toolchain xPack:

```
xpm install @xpack-dev-tools/riscv-none-elf-gcc@latest --verbose --global

xpm list --global
- @xpack-dev-tools/riscv-none-elf-gcc
  A binary xPack with the GNU RISC-V Embedded GCC executables
  - 14.2.0-3.1
```

4. From the terminal command line run Eclipse, open the workspace, and go to _File > New C/C++ Project > All > C++ Managed Build > Next>_ - note the message about the xPack RISC-V GCC toolchain:

```
./eclipse

...

Toolchain 'xPack GNU RISC-V Embedded GCC' has custom ID '2273142913' instead of '2273142912'
```

**Comment by ilg-ul** [comment]
I think that the problem itself was solved, but there were some quirks with these IDs, and when the triplet was changed from riscv-none-embed to riscv-none-elf, the name was preserved, but the id was increased.

Except that message in the console, did you notice any issues?

**Comment by TommyMurphyTM1234** [comment]
> Except that message in the console, did you notice any issues?

No - just the console message.

**Comment by ilg-ul** [comment]
> ./eclipse

Don't you encounter issues when starting eclipse by hand in a terminal?

**Comment by TommyMurphyTM1234** [comment]
> Don't you encounter issues when starting eclipse by hand in a terminal?

What issues?

**Comment by ilg-ul** [comment]
> - What issues?
 
- https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/626

**Comment by TommyMurphyTM1234** [comment]
> > * What issues?
> 
> * [Creation of Hello World RISC-V xPack Project hangs #626](https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/626)

Oh - I didn't go that far with this test as I was just trying to pinpoint cause of the `Toolchain 'xPack GNU RISC-V Embedded GCC' has custom ID '2273142913' instead of '2273142912'` message. Initially I thought that I had done something wrong while installing the xPACK RISC-V GCC toolchain using `xpm` but then realised that this seems to be an Eclipse/Emedded CDT issue.
