### ISSUE TITLE
CMSIS Packs - Read error dialog Abort button has the same effect as Ignore

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [eclipse-embed-cdt/eclipse-plugins#565]
Using Eclipse 2023.03 for Embedded C/C++ Developers including CMSIS Packs plugin 6.3.1,
When there is a problem processing a CMSIS Pack index entry and the _Read error_ dialog is presented then the _Ignore_ and _Abort_ buttons have the same effect - they both skip the current problematic item and continue on with the rest. 
That is the correct behaviour for _Ignore_ but _Abort_ should presumably stop all CMSIS Pack "refresh" processing altogether?
The issue originally arose and was reported here:

* https://github.com/eclipse-embed-cdt/eclipse-plugins/discussions/518#discussioncomment-5977154

**Comment by ilg-ul** [comment]
Fixed on 2023-05-26.
