### ISSUE TITLE
'xpm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by AndrewFrank-zxy** [eclipse-embed-cdt/eclipse-plugins#582]
### Description

I installed xpm globally (node global path is on D drive, defined in system path), installed xpack-qemu and xpack-arm-gcc manually, path is in appdata/roaming/xpack/... , when I create a new qemu xpack project in eclipse cdt, it prompts that xpm is not a valid command, and typing echo %PATH% in the built-in terminal shows the old system path.

### Steps to Reproduce

1.  installed xpm globally
1. installed xpack-qemu and xpack-arm-gcc manually
1.  create a new qemu xpack project in eclipse cdt
1.  See error

### Versions

    windows11
    Eclipse 2023-06-R
    CDT11.2.0

**Comment by ilg-ul** [comment]
https://xpack.github.io/install/
