### ISSUE TITLE
How to pass  -Wl,--start-group -lc_nano -lgcc  -Wl,--end-group 

### ISSUE THREAD

**Issue by fanghuaqi** [eclipse-embed-cdt/eclipse-plugins#590]
Hi @ilg-ul ,

When build with IDE generated Makefile, is there a way to group the requried library using `-Wl,--start-group $(LIBS) -Wl,--end-group`, so we can solve undefined symbol issue.

Thanks

**Comment by ilg-ul** [comment]
You can add additional linker options, but I'm not sure you can use variables (like `LIBS`), so you probably have to list the libraries explicitly.

For support, please use the the project Discussions.
