### ISSUE TITLE
embed-CDT cannot start openocd normally

### ISSUE THREAD

**Issue by YuraGakki** [eclipse-embed-cdt/eclipse-plugins#593]
I used a modified openocd and tried to start openocd for debugging through CDT, but I received a timeout error and the console did not provide any output. But it can be started in the shell with the same commands and parameters. 

My OpenOCD will eventually run to the server_loop(), blocked by select(), which is consistent with the official openocd. In my testing, after the CDT called openocd, my openocd did indeed run to the server_loop().

Strangely, when OpenOCD runs to the server_loop(), it indicates that OpenOCD has already connected to the device and is waiting for GDB to communicate with it through the TCP port. At this point, there is no output from the console, and the CDT seems to be waiting for OpenOCD to start. 

So how does CDT determine whether OpenOCD has been successfully started? Where may the problem be?
Thank you in advance for any comments on this issue!

#### version
CDT 10.7.1
Eclipse platform 4.25
embed-cdt 6.1.2
OS: Linux/Windows
Java: Java SE 17

![1](https://github.com/eclipse-embed-cdt/eclipse-plugins/assets/60292504/a9951675-2cd2-4732-9625-0bdfe720169c)
![2](https://github.com/eclipse-embed-cdt/eclipse-plugins/assets/60292504/57c22e1e-7221-4a41-a748-e46b7312c5e5)
![3](https://github.com/eclipse-embed-cdt/eclipse-plugins/assets/60292504/b57cf88f-49f0-4b09-8443-9382dc85238d)

**Comment by TommyMurphyTM1234** [comment]
> So how does CDT determine whether OpenOCD has been started?

This?

* https://eclipse-embed-cdt.github.io/debug/openocd/#quote-the-entire-echo-command

**Comment by YuraGakki** [comment]
> > So how does CDT determine whether OpenOCD has been started?
> 
> This?
> 
> * https://eclipse-embed-cdt.github.io/debug/openocd/#quote-the-entire-echo-command

@TommyMurphyTM1234
Thanks!
That's exactly the reason. My openOCD is unable to receive echo instructions properly. After fixing this, I can now use CDT for debugging work. 
Thanks again!
