### ISSUE TITLE
debug topToRemove bug

### ISSUE THREAD

**Issue by simonjhy** [eclipse-embed-cdt/eclipse-plugins#614]
https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/a99b863f5d6da589751bebfe5334f9b71c8bfdb4/plugins/org.eclipse.embedcdt.debug.gdbjtag.core/src/org/eclipse/embedcdt/debug/gdbjtag/core/dsf/GnuMcuFinalLaunchSequence.java#L101-L102

why in 101 use topToRemove array, but the 102 use **jtagToRemove**  index key and try to remove from orderList. It seems to use topToRemove?

**Comment by ilg-ul** [comment]
You are right, this is a bug.

**Comment by simonjhy** [comment]
@ilg-ul I want to add a new function that can always get an expression value when use start to debug application. Can you give some advice about it?

**Comment by ilg-ul** [comment]
> add a new function that can always get an expression value when use start to debug application

Can you provide more details on this expression and its use case?

**Comment by simonjhy** [comment]
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#pragma GCC diagnostic ignored "-Wreturn-type"

int main(int argc, char* argv[])
{
  // At this stage the system clock should have already been configured
  // at high speed.
	int seconds = 0;
  // Infinite loop
	while (1)
	{
		seconds++;
	}
}
like this code, I want the variable "seconds" will be always shown in a view when I start a debug session.

**Comment by ilg-ul** [comment]
Apart the fact that `seconds` will be increased much faster than every second, I think that you should be able to achieve something similar with existing functionality, possibly with some elaborate watch expressions.

Unfortunately I don't remember details now...

**Comment by ilg-ul** [comment]
Please do not add further comment not related to the issue subject.

**Comment by ilg-ul** [comment]
Fixed in 6.6.1.
