### ISSUE TITLE
CMSIS-PACK: ability to run the pack refresh in the background

### ISSUE THREAD

**Issue by ErichStyger** [eclipse-embed-cdt/eclipse-plugins#70]
Doing a refresh of the package manager (to check the packs) takes a very long time (about 10 minutes or so on my machine. During that time there is modal dialog, and I cannot run the update in the background, so I have to wait.

I wish I could do this update in the background (similar to the build process).

![updating packs](https://cloud.githubusercontent.com/assets/3187954/13029030/872752c4-d280-11e5-8015-9bc5dead1a15.jpg)

**Comment by ilg-ul** [comment]
right. the entire Packs manager will get a refurbish, I'll probably add a button to move the job to background.

**Comment by marek-trmac** [comment]
It would be good to show package name, even the package is not downloaded yet. The details could be downloaded after the user clicks on the package.

**Comment by ilg-ul** [comment]
> show package name, even the package is not downloaded yet

isn't it?

@marek-trmac, can you be more specific?

**Comment by marek-trmac** [comment]
By default, Packs view is empty (see atatched screenshot).
![capture](https://cloud.githubusercontent.com/assets/16606103/13048066/a5147550-d3e3-11e5-97f2-8717687211ee.PNG)
After the user press "Refresh" button, all packges are downloaded (this is long process), however package names are listed in http://www.keil.com/pack/index.idx and could be displayed immediatelly.

**Comment by marek-trmac** [comment]
To avoid this long process:
![capture](https://cloud.githubusercontent.com/assets/16606103/13048134/1b0e051e-d3e4-11e5-8dc0-8e437bccdc15.PNG)

**Comment by ilg-ul** [comment]
well, I considered this option when I wrote the plug-in, but it requires the plug-in to access all repository sites and download the index files during the Packs plug-in startup. what if access to one of these servers is slow and the entire step takes a few minutes? no, I think this kind of 'behind the scenes' actions may lead to poor user experience and should be avoided, I prefer to allow the user full control when to start these actions.

**Comment by marek-trmac** [comment]
I agree to preserve user control over "Refresh" functionality. This can work together with automatic refresh on background, which would be much better user experience.

**Comment by ilg-ul** [comment]
@marek-trmac, please open a new enhancement request, specifically for the initial state of the packs manager window, with explicit request that the process should happen in the background.

**Comment by cmorty** [comment]
As this is quite old and it seems like work has stalled. How much trouble would it be to make this non-modal (Add a send to background button). That way one could at least continue working while updating.

**Comment by ilg-ul** [comment]
My interest in CMSIS-PACKS is getting lower and lower.

I'll consider this, but I can't promise anything.

Do you need the packs for anything else than using the SVD during debugging?

**Comment by cmorty** [comment]
@ilg-ul No worries. I only need them for debugging and while waiting for the packs to update, which I do rather seldom, I searched the bug-tracker and found this rather old bug. :)

**Comment by ilg-ul** [comment]
For debugging only you can bring the SVD file to your project and point the debugger to it.

Actually I was thinking to make this use case the default, and avoid the hurdle with CMSIS Packs at all.

Could you try if this acceptable?

**Comment by cmorty** [comment]
@ilg-ul Using the packs is super-convenient as it allows you to select the device via the project settings dialog. Maybe having a script that downloads them, repacks the relevant data and provides that via github.io would be a convenient solution. I haven't looked into licensing issues, though.

**Comment by ilg-ul** [comment]
I know, but the way CMSIS Packs are organised, not to mention that the index is most of the time out-of-sync with actual packages, requires very creative solutions to manage them (read 'complex logic'), and I don't have time now for this. :-(

**Comment by ilg-ul** [comment]
Actually, for ST devices, I'm considering moving much closer to CubeMX.

Do you know if the packages provided now by CubeMX include the SVD files?

**Comment by cmorty** [comment]
@ilg-ul  Just checked my CubeMx repo folder: There are no SVDs and the folder structure does not look like that's likely to happen (might be they are hidden in some zip, but I don't think so).

**Comment by ilg-ul** [comment]
too bad...

:-(

**Comment by ErichStyger** [comment]
closing old issue: KDS is legacy now.
