### ISSUE TITLE
CMSIS-Pack Plugin: KLxx Series installed but it does not show up?

### ISSUE THREAD

**Issue by ErichStyger** [eclipse-embed-cdt/eclipse-plugins#72]
I have the Kinetis_KLxx_DFP installed, and the Keil/ARM CMSIS Device viewer shows the device: however it is not shown in the 'Devices' list (not black):
![kl devices](https://cloud.githubusercontent.com/assets/3187954/13036046/6fd5b07e-d35d-11e5-95c4-66a92b85f795.png)

The problem is that with that somehow the KLxx devices do not show up in the Project settings, not sure why?
![devices in build setting](https://cloud.githubusercontent.com/assets/3187954/13036061/d92270b2-d35d-11e5-8ccb-30df2b935a50.png)

**Comment by ilg-ul** [comment]
this looks like a small bug. if you exit/enter Eclipse, does it show it properly?

otherwise, for questions please use the project forum https://www.element14.com/community/groups/gnu-arm-eclipse

**Comment by ErichStyger** [comment]
enter/exit Eclipse does not change things. What is the condition that the icon under the Device view turns from 'gray' to 'black'?

**Comment by ilg-ul** [comment]
then it is definitely a bug, the mere presence in the installed packages should be enough.

**Comment by ErichStyger** [comment]
closing issue, will file a bug report

**Comment by ilg-ul** [comment]
No need to, I already marked it as a bug, don't you see this label?

**Comment by ilg-ul** [comment]
duplicate of #85.

**Comment by ErichStyger** [comment]
closing old issues
