### ISSUE TITLE
CMSIS-Pack manager: Kinetis KLxx Devices do not show up even if installed

### ISSUE THREAD

**Issue by ErichStyger** [eclipse-embed-cdt/eclipse-plugins#85]
Using:
- Window 7, 64bit,
- Kinetis Design Studio V3.1 (Eclipse Luna)
- GNU ARM C/C++ Packs (Experimental)    2.2.2.201602101653 ilg.gnuarmeclipse.packs.feature.group

I have the 'Kinetis_KLxx_DFP' pack installed from http://www.keil.com/pack/index.idx (see screenshots)
![kl device not shown](https://cloud.githubusercontent.com/assets/3187954/13196178/82a7fdec-d7c7-11e5-8889-dca8fd4de3cd.png)

As well under 'Devices' the 'KLxx Series' is grayout out, but installed:

Exit and restart Eclipse did not help.
![klxx series grayed out](https://cloud.githubusercontent.com/assets/3187954/13196187/c128a5d0-d7c7-11e5-800c-2498156b07b8.png)

Let me know if you need any further information.

Thanks,
Erich

**Comment by ilg-ul** [comment]
this is a particular case of #203

**Comment by ErichStyger** [comment]
cleaning up old issues, I think this one could be closed.
